"use client";   

import Header from "./layout/header";
import List from "./layout/list";
import Filter from "./layout/filter";

import style from "/styles/home.module.css";
import RootLayout from "./layout";

async function getList() {
    const res = await fetch('http://127.0.0.1:8090/api/collections/list/records?page=1&perPage=30');
    const data = await res.json();
    return data?.items as any[];
}   

export default async function HomePage() {
    return (
    <RootLayout>
        <head>
            <title>ManhwaDex</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"/>
            <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"/>
            <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"/>
            <link rel="manifest" href="/site.webmanifest"/>
        </head>
        <body>
            <Header/>
            <main>
                <Filter className={style.filter}/>
                <List/>
            </main>
        </body>
    </RootLayout>
  )
}