import Head from "next/head";
import Header from "./layout/header";
import List from "./layout/list";
import Filter from "/pages/layout/filter";

import style from "/styles/home.module.css";

export default function Home({type}) {
    return (
    <>
        <Head>
            <title>ManhwaDex</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"/>
            <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"/>
            <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"/>
            <link rel="manifest" href="/site.webmanifest"/>
        </Head>
        <Header/>
        <main>
            <Filter className={style.filter} type={type}/>
            <List type={type}/>
        </main>
    </>
  )
}

export async function getServerSideProps() {
    const type = "Manhwa";
    return {
        props: { type }
    }
}