import Head from "next/head";
import Image from "next/image";
import Header from "./layout/header";
import Article from "./layout/article";
import style from "/styles/home.module.css";

export default function Home( {posts}) {
    return (
    <>
        <Head>
            <title>ManhwaDex</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"/>
            <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"/>
            <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"/>
            <link rel="manifest" href="/site.webmanifest"/>
        </Head>
        <Header/>
        <main>
            <div className={style.container}>
                <Article title="Crimson Karma"/>
                <Article title="Lady Chef Royale"/>
                <Article title="Mook Hyang - Dark Lady"/>
                <Article title="Asmodian's Contract"/>
                <Article title="The Return of the 8th Class Mage"/>
                <Article title="The Golden-Haired Elementalist"/>
                <Article title="White Blood"/>
                <Article title="A Transmigrator's Privilege"/>
                <Article title="Lady Chef Royale"/>
                <Article title="Lady Chef Royale"/>
                <Article title="Lady Chef Royale"/>
                <Article title="Lady Chef Royale"/>
                <Article title="Lady Chef Royale"/>
                <Article title="Lady Chef Royale"/>
                <Article title="Lady Chef Royale"/>
                <Article title="Lady Chef Royale"/>
                <Article title="Lady Chef Royale"/>
                <Article title="Lady Chef Royale"/>
                <Article title="Lady Chef Royale"/>
                <Article title="Lady Chef Royale"/>
                <Article title="Lady Chef Royale"/>
                <Article title="Lady Chef Royale"/>
                <Article title="Lady Chef Royale"/>
                <Article title="Lady Chef Royale"/>
            </div>
        </main>
    </>
  )
}